---
deployment:
  tasks:
    - echo "=== cPanel deploy started ==="

    # Frontend build → public_html
    - echo "Deploying React frontend..."
    - /bin/rsync -av --delete frontend/dist/ /home/dratifshahzad/public_html/

    # Backend → Python App root
    - echo "Deploying Flask backend..."
    - /bin/rsync -av --delete backend/ /home/dratifshahzad/pythonapps/main-web-backend

    # Restart Passenger for backend
    - /bin/mkdir -p /home/dratifshahzad/pythonapps/main-web-backend
    - /usr/bin/touch /home/dratifshahzad/pythonapps/main-web-backend/tmp/restart.txt

    - echo "=== cPanel deploy finished ==="