deployment:
  tasks:
    - export DEPLOYPATH=/home/dratifshahzad/public_html  

    - /bin/rm -rf $DEPLOYPATH/*  

    - /bin/cp -R frontend/dist/* $DEPLOYPATH/  

    - /bin/mkdir -p /home/dratifshahzad/backend
    - /bin/cp -R backend/* /home/dratifshahzad/backend/