deployment:
  tasks:
    - export FRONTENDPATH=/home/dratifshahzad/public_html
    - export BACKENDPATH=/home/dratifshahzad/backendapp

    # Deploy frontend
    - cd frontend
    - npm install
    - npm run build
    - rm -rf $FRONTENDPATH/*
    - cp -R dist/* $FRONTENDPATH/

    # Deploy backend
    - rm -rf $BACKENDPATH/*
    - cp -R backend/* $BACKENDPATH/
