---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dratifshahzad/public_html/
    - /bin/cp -R /home/dratifshahzad/mainapp/repo/frontend/dist/* $DEPLOYPATH

    - export DEPLOYPATH=/home/dratifshahzad/public_html/api/
    - /bin/cp -R /home/dratifshahzad/mainapp/repo/backend/* $DEPLOYPATH
