---
deployment:
  tasks:
    # Set deployment path
    - export DEPLOYPATH=/home/dratifshahzad/public_html
    
    # Clean up old files first
    - rm -rf $DEPLOYPATH/backend $DEPLOYPATH/frontend $DEPLOYPATH/src $DEPLOYPATH/assets
    
    # Copy source files
    - /bin/cp -R backend $DEPLOYPATH/
    - /bin/cp -R frontend $DEPLOYPATH/
    
    # Install backend dependencies
    - cd $DEPLOYPATH/backend && /usr/local/bin/python3.9 -m pip install --user -r requirements.txt
    
    # Install frontend dependencies and build (with error checking)
    - cd $DEPLOYPATH/frontend
    - npm install --production=false
    - npm run build || (echo "React build failed!" && exit 1)
    # Debug: Check if build was successful
    - ls -la $DEPLOYPATH/frontend/dist/ || echo "Dist folder not found!"
    
    # Copy ONLY the built files from dist folder to root
    - if [ -d "$DEPLOYPATH/frontend/dist" ]; then /bin/cp -R $DEPLOYPATH/frontend/dist/* $DEPLOYPATH/; else echo "Build failed - no dist folder"; exit 1; fi
    
    # Remove source files from public directory (security)
    - rm -rf $DEPLOYPATH/frontend $DEPLOYPATH/src
    
    # Create Python app in subdirectory
    - mkdir -p $DEPLOYPATH/myapp
    - /bin/cp -R $DEPLOYPATH/backend $DEPLOYPATH/myapp/
    
    # Create passenger_wsgi.py for Python app
    - |
      cat > $DEPLOYPATH/myapp/passenger_wsgi.py << 'EOF'
      import sys
      import os
      
      # Add paths
      sys.path.insert(0, os.path.dirname(__file__))
      sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'backend'))
      
      from app import create_app
      application = create_app()
      
      if __name__ == "__main__":
          application.run()
      EOF
    
    # Create .htaccess for React Router (SPA support)
    - |
      cat > $DEPLOYPATH/.htaccess << 'EOF'
      RewriteEngine On
      
      # Handle API requests - send to Python app
      RewriteCond %{REQUEST_URI} ^/api/.*
      RewriteRule ^(.*)$ /myapp/$1 [L,QSA]
      
      # Handle React Router - all other requests go to index.html
      RewriteCond %{REQUEST_FILENAME} !-f
      RewriteCond %{REQUEST_FILENAME} !-d
      RewriteCond %{REQUEST_URI} !^/api/.*
      RewriteRule . /index.html [L]
      EOF
    
    # Set permissions
    - find $DEPLOYPATH/myapp -type f -name "*.py" -exec chmod 644 {} \;
    - chmod 644 $DEPLOYPATH/myapp/passenger_wsgi.py
    - chmod 644 $DEPLOYPATH/.htaccess
    
    # Initialize database
    - cd $DEPLOYPATH/myapp/backend && /usr/local/bin/python3.9 -c "from app import create_app, db; app = create_app(); app.app_context().push(); db.create_all()" || echo "DB init failed - will try later"