---
deployment:
  tasks:
    - export FLASK_PATH=/home/dratifshahzad/myapp
    - export PUBLIC_PATH=/home/dratifshahzad/public_html
    
    - /bin/rsync -avz --exclude '.git' myapp/backend/ $FLASK_PATH/
    - /bin/rsync -avz myapp/frontend/dist/ $PUBLIC_PATH/
    
    - cd $FLASK_PATH && python -m pip install -r requirements.txt
    
    - mkdir -p $FLASK_PATH/tmp
    - touch $FLASK_PATH/tmp/restart.txt
    
    - find $FLASK_PATH -type f -exec chmod 644 {} \;
    - find $FLASK_PATH -type d -exec chmod 755 {} \;
    - find $PUBLIC_PATH -type f -exec chmod 644 {} \;
    - find $PUBLIC_PATH -type d -exec chmod 755 {} \;
    
    - |
      cat > $PUBLIC_PATH/.htaccess << 'EOF'
      RewriteEngine On
      
      RewriteCond %{REQUEST_URI} ^/api/
      RewriteRule ^api/(.*)$ /cgi-bin/myapp/$1 [L,P,QSA]
      
      RewriteCond %{REQUEST_FILENAME} !-f
      RewriteCond %{REQUEST_FILENAME} !-d
      RewriteCond %{REQUEST_URI} !^/api/
      RewriteRule . /index.html [L]
      EOF