---
deployment:
  tasks:
    # Set deployment path
    - export DEPLOYPATH=/home/dratifshahzad/public_html
    
    # Clean up old deployment files
    - rm -rf $DEPLOYPATH/backend $DEPLOYPATH/myapp $DEPLOYPATH/assets $DEPLOYPATH/index.html
    
    # Copy backend files
    - /bin/cp -R backend $DEPLOYPATH/
    
    # Copy pre-built React files directly from dist folder
    - /bin/cp -R frontend/dist/* $DEPLOYPATH/
    
    # Install Python dependencies
    - cd $DEPLOYPATH/backend && /usr/local/bin/python3.9 -m pip install --user -r requirements.txt
    
    # Create Python app directory
    - mkdir -p $DEPLOYPATH/myapp
    - /bin/cp -R $DEPLOYPATH/backend $DEPLOYPATH/myapp/
    
    # Create passenger_wsgi.py for the Python app
    - |
      cat > $DEPLOYPATH/myapp/passenger_wsgi.py << 'EOF'
      import sys
      import os
      
      # Add project paths to Python path
      sys.path.insert(0, os.path.dirname(__file__))
      sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'backend'))
      
      # Set environment variables for production
      os.environ.setdefault('SECRET_KEY', 'your-production-secret-key-here')
      os.environ.setdefault('JWT_SECRET_KEY', 'your-production-jwt-secret-here')
      os.environ.setdefault('DATABASE_URL', 'sqlite:///app.db')
      
      # Import Flask app
      from app import create_app
      application = create_app()
      
      if __name__ == "__main__":
          application.run()
      EOF
    
    # Create .htaccess for routing
    - |
      cat > $DEPLOYPATH/.htaccess << 'EOF'
      RewriteEngine On
      
      # Route API requests to Python app
      RewriteCond %{REQUEST_URI} ^/api/.*
      RewriteRule ^api/(.*)$ /myapp/api/$1 [L,QSA]
      
      # Handle React Router - send all other requests to index.html
      RewriteCond %{REQUEST_FILENAME} !-f
      RewriteCond %{REQUEST_FILENAME} !-d
      RewriteCond %{REQUEST_URI} !^/api/.*
      RewriteRule . /index.html [L]
      EOF
    
    # Set proper file permissions
    - find $DEPLOYPATH/myapp -type f -name "*.py" -exec chmod 644 {} \;
    - chmod 644 $DEPLOYPATH/myapp/passenger_wsgi.py
    - chmod 644 $DEPLOYPATH/.htaccess
    - chmod 644 $DEPLOYPATH/index.html
    
    # Initialize database (create tables)
    - cd $DEPLOYPATH/myapp/backend && /usr/local/bin/python3.9 -c "from app import create_app, db; app = create_app(); app.app_context().push(); db.create_all()" || echo "Database initialization will be done manually"