---
deployment:
  tasks:
    # Set deployment path to a subdirectory
    - export DEPLOYPATH=/home/dratifshahzad/public_html/flask_backend
    - mkdir -p $DEPLOYPATH
    
    # Copy backend and frontend
    - /bin/cp -R backend $DEPLOYPATH/
    - /bin/cp -R frontend $DEPLOYPATH/
    
    # Install backend dependencies
    - cd $DEPLOYPATH/backend && /usr/local/bin/python3.9 -m pip install --user -r requirements.txt
    
    # Build React app
    - cd $DEPLOYPATH/frontend && npm install && npm run build
    
    # Copy React build to main public_html root (for the frontend)
    - /bin/cp -R $DEPLOYPATH/frontend/dist/* /home/dratifshahzad/public_html/
    
    # Create passenger_wsgi.py in the app directory
    - |
      cat > $DEPLOYPATH/passenger_wsgi.py << 'EOF'
      import sys
      import os
      
      sys.path.insert(0, os.path.dirname(__file__))
      sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'backend'))

      from app import create_app
      application = create_app()
      EOF
    
    # Set permissions
    - find $DEPLOYPATH -type f -name "*.py" -exec chmod 644 {} \;
    - chmod 644 $DEPLOYPATH/passenger_wsgi.py