deployment:
  tasks:
    - export DEPLOYPATH=/home/dratifshahzad/public_html
    # Clear old frontend
    - /bin/rm -rf $DEPLOYPATH/*
    # Copy React build
    - /bin/cp -R frontend/dist/* $DEPLOYPATH/
    # Copy backend (Flask app files, not venv)
    - /bin/cp -R backend $DEPLOYPATH/backend
