deployment:
  tasks:
    - export FRONTEND=/home/dratifshahzad/public_html
    - export BACKEND=/home/dratifshahzad/backendapp

    # Build frontend
    - cd frontend
    - npm install
    - npm run build

    # Deploy frontend
    - rm -rf $FRONTEND/*
    - cp -R dist/* $FRONTEND/

    # Go back to repo root
    - cd ..

    # Deploy backend
    - rm -rf $BACKEND/*
    - cp -R backend/* $BACKEND/
