deployment:
  tasks:
    - export FRONTEND=/home/dratifshahzad/public_html
    - export BACKEND=/home/dratifshahzad/backendapp

    # Frontend build and deploy
    - cd frontend
    - npm install
    - npm run build
    - rm -rf $FRONTEND/*
    - cp -R dist/* $FRONTEND/

    # Backend deploy
    - rm -rf $BACKEND/*
    - cp -R backend/* $BACKEND/
