---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dratifshahzad/public_html/
    - /bin/cp -R frontend/dist/* $DEPLOYPATH
    - export BACKENDPATH=/home/dratifshahzad/myapp/
    - /bin/cp -R backend/* $BACKENDPATH
