"""Descriptive message about the changes

Revision ID: 03cec7ec18d4
Revises: 
Create Date: 2025-09-18 17:02:02.102645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03cec7ec18d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ncaaa__course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.VARCHAR(length=6), nullable=False),
    sa.Column('course_name', sa.String(length=144), nullable=False),
    sa.Column('course_type', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_code'),
    sa.UniqueConstraint('course_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ncaaa__course')
    # ### end Alembic commands ###
