"""empty message

Revision ID: 4763c55b1303
Revises: a0aa1b185e90
Create Date: 2025-10-07 00:27:59.543558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4763c55b1303'
down_revision = 'a0aa1b185e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ncaaa__course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_description', sa.Text(), nullable=True))
        batch_op.drop_column('course_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ncaaa__course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_type', mysql.VARCHAR(length=16), nullable=True))
        batch_op.drop_column('course_description')

    # ### end Alembic commands ###
