"""added new models and updated previous ones

Revision ID: a8092dfe7e8e
Revises: ae86ed6fb7d7
Create Date: 2025-09-27 23:37:28.596566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8092dfe7e8e'
down_revision = 'ae86ed6fb7d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    op.create_table('student_course',
    sa.Column('student_course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('student_course_id')
    )
    op.create_table('quiz_marks',
    sa.Column('quiz_mark_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.quiz_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('quiz_mark_id')
    )
    op.drop_table('enrollments')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('course_description',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kauid', sa.Integer(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['kauid'])
        batch_op.drop_column('kau_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kau_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('created_at',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('kauid')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('course_description',
               existing_type=mysql.TEXT(),
               nullable=False)

    op.create_table('enrollments',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], name=op.f('enrollments_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], name=op.f('enrollments_ibfk_2')),
    sa.PrimaryKeyConstraint('user_id', 'course_id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('quiz_marks')
    op.drop_table('student_course')
    op.drop_table('quizzes')
    # ### end Alembic commands ###
